# Configuration file for both Performance and Best Practice checks for Tableau Workbooks

# Tableau server configuration
tableau_server:
    server: <TABLEAU_SERVER_HOST>                   # Tableau Server or Online address (e.g. https://your_server_domain:8000)
    username: <ADMIN_USER>                          # User to sign in to the Tableau Server REST API
    password: <ADMIN_PASSWORD>                      # Password of user
    site: <TABLEAU_SERVER_SITE>                     # Leave empty for default site

# Workbooks (wbs) Tag
tags:
    search_tag: <SEARCH_TAGS_LIST>                  # Comma separated list of tags to search for wbs. These tags are used only in the performance check script (e.g. #readyForMigration)
    reject_tag: "<REJECTED_TAG>"                    # Tag to be set to poor performant wbs after performance checks. The best practice script will use this tag to retrieve wbs to analyse


# Performance thresholds:
performance_thresholds:
    max_views: <MAX_VIEWS>                          # Maximum number of views to that a workbook can have to be considered as performant (set to 50 by default)
    max_elapsed_time: <MAX_ELAPSED_TIME>            # Maximum time in seconds that a view must take to render to be migrated (set to 10 by default)

# SMTP connection
smtp:
    smtp_host: <SMTP_HOST>                          # SMTP server
    smtp_port: <SMTP_PORT>                          # SMTP port
    smtp_user: <SMTP_USER>                          # User to login to the SMTP server
    smtp_password: <SMTP_PASSWORD>                  # Password of SMTP user
    smtp_from_email: <SMTP_FROM_EMAIL>              # From address to use as sender

# SLACK
slack:
    slack_token: <SLACK_TOKEN>                      # Slack token api
    slack_channel: <SLACK_CHANNEL>                  # Slack channel to post best practices feedback

logging_level: <LOGGING_LEVEL>                      # Desired logging level (set to error by default).choices=['debug', 'info', 'error']       